version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: joona8pheem6muj1ahPhahleigogoquejoo8eeneeRo9ahcai1Xeishech4ohTha
serial:
  port: /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_E072A1D909C8-if00
  baudrate: 460800
  rtscts: true
  adapter: ember
advanced:
  log_level: info
  channel: 11
  network_key:
    - 114
    - 37
    - 115
    - 5
    - 23
    - 246
    - 232
    - 47
    - 164
    - 49
    - 68
    - 63
    - 43
    - 32
    - 154
    - 230
  pan_id: 25912
  ext_pan_id:
    - 29
    - 15
    - 61
    - 188
    - 198
    - 47
    - 148
    - 61
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x54ef4410014ae72a':
    friendly_name: roller_door_contact
    retain: true
  '0xa4c138074803a9a9':
    friendly_name: Plug 1
    retain: true
  '0xa4c138ba345696ae':
    friendly_name: Plug 2
    retain: true
  '0x54ef4410014ae8c0':
    friendly_name: Fire Exit Door (WEST)
    retain: true
  '0xa4c13851f47cb91d':
    friendly_name: Lane 1 Left
    retain: true
  '0xa4c138bc9b38b0c2':
    friendly_name: '0xa4c138bc9b38b0c2'
  '0xa4c138fdcd4c98b3':
    friendly_name: Lane 2 Left
    retain: true
  '0xa4c13879a2af63a1':
    friendly_name: Lane 2 Right
    retain: true
  '0xa4c138d3ea816fa6':
    friendly_name: Lane 3 Left
    retain: true
  '0xa4c13861a6ad537a':
    friendly_name: Lane 3 Right
    retain: true
availability:
  enabled: true
